version: "3.8"

services:
  backend:
    image: blacksaiyan/projet-fil-rouge-jenkins:backend-latest
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=odc.settings
      - POSTGRES_HOST=database
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=odc
      - POSTGRES_PASSWORD=odc123
      - POSTGRES_DB=odcdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: blacksaiyan/projet-fil-rouge-jenkins:frontend-latest
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
